package com.waggle.domain.reference.enums;

public enum Industry {
    FINANCE,
    REAL_ESTATE,
    INTERIOR,
    MEDICAL_HEALTHCARE,
    ECOMMERCE,
    ENTERTAINMENT,
    TRAVEL,
    SOCIAL_NETWORK,
    CULTURE_ART,
    BEAUTY_FASHION,
    RELIGION,
    SALES_DISTRIBUTION,
    EDUCATION,
    CONSTRUCTION,
    HEALTH,
    PARENTING,
    MEDIA_ADVERTISING,
    ETC
}
